### ISSUE TITLE
Build fails on Lion

### ISSUE THREAD

**Issue by smurn** [ludwigschwardt/python-gnureadline#28]
Hi,

Building on Lion I got the 

```
gcc: readline/libreadline.a: No such file or directory
gcc: readline/libhistory.a: No such file or directory
```

errors that others got in #13, but I doubt it is related as further analysis showed that it is a OSX specific issue. 

The setup.py output pointed me to config.log which told me that the ppc compilers are missing.

I'm by no means an OSX expert, but I guess the problem is the following:

The build.sh you provide has an `if` because

```
# Starting with 10.6 (Snow Leopard), only Intel architecture is supported
```

However, it is comparing the most recent SDK version, not the OS version, against 10.6.

This particular machine has OSX 10.7, but the most recent SDK is only 10.5 (don't ask my why. It is not a develoment machine, no xcode is installed). The result is that build.sh tries to make ppc and ppc64 builds too. `./configure` fails, libreadline.a is not built, resulting in the error message.

Sorry for not providing a patch, I'm new to OSX and really have no idea how I'd get the OS version in the shell. I currently just remove the ppc related arch flags which does the trick.

P.S. are you sure that `for sdk_dir in /Developer/SDKs/*; do` is sorting correctly? 

Thanks for providing python-readline!
-Stefan

**Comment by ludwigschwardt** [comment]
We will hopefully encounter fewer of these kinds of corner cases with the latest set of precompiled MacPython wheels on both Linux and macOS (although Gentoo is probably a lost cause :-)). I'm closing this in the meantime.
