### ISSUE TITLE
Update the PyPI readline page to refer users to gnureadline

### ISSUE THREAD

**Issue by ned-deily** [ludwigschwardt/python-gnureadline#38]
The PyPI page for the legacy readline distribution has no references to the new gnureadline one.  I suspect many people are still unaware of the renaming and transition.  I was until now and I see the MacPorts project was (I've filed an issue there).

**Comment by ludwigschwardt** [comment]
I've finally added some warnings and redirections from readline to gnureadline on PyPI.
