### ISSUE TITLE
Weird behavior on Mavericks

### ISSUE THREAD

**Issue by amanzotti** [ludwigschwardt/python-gnureadline#41]
Hi 
I am facing a weird behavior on my mac osx 10.9.5 

<code>
alessandromanzotti@Macintosh-3:~$ uname -a
Darwin Macintosh-3.local 13.4.0 Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64 x86_64
</code>

When I installed the py27-readline package with all the python versions, i.e. 

the mac system one
miniconda, conda
installed from source

My Python shell does not recognized the spacebar anymore. When I press it I heard the terminal beep.
My PYTHONSTARTUP is clean and I got the problem even running python with  python -E.

This happen both when I installed readline with pip and macport.

You can find more info here in the macport tickets
See also https://trac.macports.org/ticket/45301.

But I think it should come from some weird interaction between my system and readline.

Thanks

A/.

**Comment by ludwigschwardt** [comment]
This is quite weird... Did you or the MacPorts folks ever figure out the cause, or should I leave the issue open?

**Comment by ludwigschwardt** [comment]
It looks like MacPorts gave up on this last year, so maybe it's time for me too...
