### ISSUE TITLE
Installation error in cygwin / Windows

### ISSUE THREAD

**Issue by alanoursland** [ludwigschwardt/python-gnureadline#42]
I get the following error when I try to install gnureadline. I can't find any other reports online and hope this is the best place to get a solution. Let me know if you need any more information.

$ easy_install gnureadline
Searching for gnureadline
Reading https://pypi.python.org/simple/gnureadline/
Best match: gnureadline 6.3.3
Downloading https://pypi.python.org/packages/source/g/gnureadline/gnureadline-6.3.3.tar.gz#md5=c4af83c9a3fbeac8f2da9b5a7c60e51c
Processing gnureadline-6.3.3.tar.gz
Writing /tmp/easy_install-25EGvx/gnureadline-6.3.3/setup.cfg
Running gnureadline-6.3.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-25EGvx/gnureadline-6.3.3/egg-dist-tmp-zZmeJ0
In file included from Modules/2.x/readline.c:31:0:
./readline/readline.h:385:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 extern int rl_message ();
 ^
Modules/2.x/readline.c:963:23: warning: ‘_PyOS_ReadlineTState’ redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
 extern PyThreadState* _PyOS_ReadlineTState;
                       ^
gcc: error: readline/libreadline.a: No such file or directory
gcc: error: readline/libhistory.a: No such file or directory
error: Setup script exited with error: command 'gcc' failed with exit status 1

**Comment by alanoursland** [comment]
I thought I'd take a shot at fixing this myself. I cloned the github repository, unpacked readline-6.3.tar.gz, applied the patches and built without errors.

I don't know.

Is there a way I can install this from the clone? Or build a package that pip can install?

**Comment by alanoursland** [comment]
I get the error when I try to build the egg "python setup.py sdist bdist_egg".

**Comment by alanoursland** [comment]
I saw the line in setup.py that prevents win32 and suggests pyreadline instead. I'll try to move forward with that, although I'm trying to a specific ipython notebook and don't know if I'll run into problems.

I wonder if 'cygwin' should also be prevented like 'win32'.

I've tried installed readline from the cygwin installed. It didn't help (and was using an older version than 6.3.3)

**Comment by ludwigschwardt** [comment]
Hi,

I've never tested this on Cygwin... My first question would be if Cygwin already provides readline and whether your installed Python makes use of it. If so, you do not need this package.

I see on cygwin.com that the latest readline is available as the libreadline7-6.3.8-1 package (and corresponding libreadline-devel-6.3.8-1). As long as you then use the standard Cygwin Python package, all should be well. Readline functionality has barely changed over the years, so I don't think there is a strong need to get the latest and greatest version anyway.

Let me know why you tried out this package instead or of any complications with your setup.

**Comment by alanoursland** [comment]
I tried using this package because I'm trying to set up an environment for assignment 1 of cs231n (http://cs231n.stanford.edu/). It is in a list of required packages for an ipython notebook.

I had tried installing several cygwin packages that looked like readline (including ncurses), but I wasn't sure I was missing something. I wiped my cygwin installation and restarted from scratch installing everything. I still got the same error.

    ./readline/readline.h:385:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     extern int rl_message ();

This looks like either a flag configuration error or use of a C compiler for C++ code.

Stack library has a description of the error:
http://stackoverflow.com/questions/42125/function-declaration-isnt-a-prototype

"In C int foo() and int foo(void) are different functions. int foo() accepts an arbitrary number of arguments, while int foo(void) accepts 0 arguments. In C++ they mean the same thing. I suggest that you use void consistently when you mean no arguments."

If I untar, patch and configure readline-lib manually (in the rl subdir of this github), I get a link error instead of a compile error:

gcc -shared -Wl,--enable-auto-import -Wl,--enable-auto-image-base -Wl,--export-all -Wl,--out-implib=cygreadline6.dll.a  -o cygreadline6.dll readline.so vi_mode.so funmap.so keymaps.so parens.so search.so rltty.so complete.so bind.so isearch.so display.so signals.so util.so kill.so undo.so macro.so input.so callback.so terminal.so text.so nls.so misc.so history.so histexpand.so histfile.so histsearch.so shell.so mbutil.so tilde.so colors.so parse-colors.so xmalloc.so xfree.so compat.so -lcurses
readline.so: In function `readline_internal_char':
/home/Alan/github/python-gnureadline/rl/readline-lib/shlib/../readline.c:538: undefined reference to `sigsetjmp'
/home/Alan/github/python-gnureadline/rl/readline-lib/shlib/../readline.c:538:(.text+0xb5b): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `sigsetjmp'
util.so: In function `_rl_abort_internal':
/home/Alan/github/python-gnureadline/rl/readline-lib/shlib/../util.c:112: undefined reference to `siglongjmp'
/home/Alan/github/python-gnureadline/rl/readline-lib/shlib/../util.c:112:(.text+0x115): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `siglongjmp'
callback.so: In function `rl_callback_read_char':
/home/Alan/github/python-gnureadline/rl/readline-lib/shlib/../callback.c:129: undefined reference to `sigsetjmp'
/home/Alan/github/python-gnureadline/rl/readline-lib/shlib/../callback.c:129:(.text+0xf0): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `sigsetjmp'
collect2: error: ld returned 1 exit status
Makefile:176: recipe for target 'cygreadline6.dll' failed

It looks like it is trying to use the curses library. I don't know if that is correct or not or how I might tell it to link to something else. In any event, the setup.py script is configuring the build in a different way.

**Comment by ludwigschwardt** [comment]
Hi,

First off, I am very sorry that you had to go down this crazy rabbithole...

If all you need is IPython on a Windows machine, I would get one of the standalone Python distributions for Windows, like [Anaconda](http://continuum.io/downloads) or [Canopy](https://www.enthought.com/products/canopy/). This is by far the easiest way to get IPython notebook support on Windows.

If you still feel adventurous and want to go the Cygwin route, I would first check whether Python is not already using readline. The readline library is stock standard on nearly all open-source platforms and really should only be installed in an emergency. Try the following: start `python` in your Cygwin terminal and see whether you have tab completion - type `im` followed by <TAB> and you should see e.g. `import`. If this is not happening, then you need to consider this package.

The problem is that I compile a static version of the library within my module and this is something I have never tested or debugged on Cygwin, not having it around. You are welcome to help me debug this, but in the interest of your assignments it might be easier going the Anaconda / Canopy route :-)

I should really edit the IPython documentation and describe the conditions for installing readline. It has caused a lot of confusion over the years.

**Comment by alanoursland** [comment]
I'm going down the crazy rabbit hole voluntarily. It would probably be easier to just make a bootable thumbdrive Ubuntu installation, but I have other reasons for wanting this to work. I'm also doing the class on my own time unofficially so I'm not on a schedule.

I'm happy to do work to get this fixed if you want to help. Build systems aren't my strong point (and I think the problem is in the build config.) At the very least maybe we can determine if this is even necessary on cygwin and can put a message in the setup.py if it isn't. sys.platform returns 'cygwin'.

 im-<tab> does not autocomplete.

I don't know how much this will impact using the notebook.

**Comment by ludwigschwardt** [comment]
Great!

From [the docs](https://docs.python.org/2/tutorial/interactive.html) it seems that Cygwin should have this support already.

I am a bit rusty on this... Of course `python` won't autocomplete - that's why people use `ipython`! Try `im` + TAB in `ipython` instead (which should install fine without readline, by the way).

**Comment by alanoursland** [comment]
Autocomplete does work in ipython.

**Comment by ludwigschwardt** [comment]
Excellent!

I will then add a line to setup.py for now that mentions that Cygwin does not need this and probably won't compile anyway. If someone *really* needs to compile it in future I could re-open the rabbit hole.

Thanks for testing this and have fun with the course.

**Comment by tibbon** [comment]
I'm hitting this too now, attempting to install gnureadline on my Raspberry Pi

**Comment by ludwigschwardt** [comment]
First off, what distribution is running on the Pi? I strongly suspect that you already have readline installed and therefore have no need for this package.

**Comment by stucka** [comment]
I'm getting this error on Ubuntu 16.04 32-bit (ancient laptop), attempting to use pip to install gnureadline-6.3.3. (It's needed for a Tarbell install.) I actually already had the Ubuntu package for libreadline6 and installed libreadline6-dev ... so maybe I can convince Tarbell to work without this, maybe I can't.

The error message:
i686-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DHAVE_RL_CALLBACK -DHAVE_RL_CATCH_SIGNAL -DHAVE_RL_COMPLETION_APPEND_CHARACTER -DHAVE_RL_COMPLETION_DISPLAY_MATCHES_HOOK -DHAVE_RL_COMPLETION_MATCHES -DHAVE_RL_COMPLETION_SUPPRESS_APPEND -DHAVE_RL_PRE_INPUT_HOOK -I. -I/usr/include/python2.7 -c Modules/2.x/readline.c -o build/temp.linux-i686-2.7/Modules/2.x/readline.o
    In file included from Modules/2.x/readline.c:31:0:
    ./readline/readline.h:385:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     extern int rl_message ();
     ^
    i686-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-i686-2.7/Modules/2.x/readline.o readline/libreadline.a readline/libhistory.a -lncurses -o build/lib.linux-i686-2.7/gnureadline.so
    /usr/bin/ld: cannot find -lncurses
    collect2: error: ld returned 1 exit status
    error: command 'i686-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-r_feVK/gnureadline/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-3WELXt-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-r_feVK/gnureadline/
