### ISSUE TITLE
Any chance of a Python 3.5 OSX wheel?

### ISSUE THREAD

**Issue by matthew-brett** [ludwigschwardt/python-gnureadline#46]
Would you consider uploading a wheel for Python 3.5 and OSX?   It would really help installing on a computer without a compiler.  

Thanks a lot.

**Comment by ludwigschwardt** [comment]
Hi Matthew,

I'm keen to do some work on the package in the near future. Which Python
3.5 do you use (python.org?) and which OS X?

Regards,
Ludwig

**Comment by matthew-brett** [comment]
Can I humbly suggest building the package against Python.org Python, so that it is usable from system python, homebrew, macports etc?  I wrote this up here:  https://github.com/MacPython/wiki/wiki/Spinning-wheels

I would be very happy to make a wheel-building repo for you on MacPython if that would be of interest:

https://github.com/MacPython

**Comment by matthew-brett** [comment]
Oh - sorry - building on Python.org Python makes the wheels compatible with OSX >= 10.6 .  For older pip you would need to add parts to the wheel filename to signal that the wheels are compatible with modern OSX - see e.g. https://github.com/MacPython/cython-wheels/blob/master/.travis.yml#L26

**Comment by ludwigschwardt** [comment]
Oh, I remember your wheel page and the work on getting matplotlib wheeled
up - very cool!

I will definitely look into your tools. My current setup went over the
top as I installed about 10 different Pythons and as many virtualenvs just
to make wheels for them. And this coming from someone who has always
advocated having only one Python on your system (system Python... I know, I
know!). No wonder I haven't repeated the experiment.

**Comment by matthew-brett** [comment]
I built you a shell repo, not running tests, probably failing - at https://github.com/MacPython/python-gnureadline-wheels

**Comment by matthew-brett** [comment]
It's possible the MacPython builds actually work with the current repo.  

https://travis-ci.org/MacPython/python-gnureadline-wheels/builds/81308495

Wheels get uploaded to https://wheels.scipy.org

**Comment by ludwigschwardt** [comment]
I downloaded the 2.7 wheel and it installed fine on my OS X 10.9.5. Woot!

No more keeping around older OSes to test installs, I hope...

Thanks again for this!

**Comment by matthew-brett** [comment]
No problem at all - thanks for fixing the readline problem so successfully.

**Comment by ludwigschwardt** [comment]
Actually it's all due to @etrepum, I'm just the lowly maintainer :-)

**Comment by ludwigschwardt** [comment]
Wheel uploaded for 6.3.3, updating to 6.3.8 soon...

**Comment by matthew-brett** [comment]
Great - thanks for doing that.

**Comment by ludwigschwardt** [comment]
Hi Matthew,

Are your wheels El Capitan ready, or should I wait for updates? I want to
bring out a new version of python-gnureadline and ensure that it is
compatible with 10.11.

L.

**Comment by matthew-brett** [comment]
I don't have a copy of El Capitan but I believe they are compatible.

For 10.9, 10.10 I added extra tags to the filename, but that was to get round the behavior of pip < 6.0, which did not recognize older versions of OSX as being compatible with newer - e.g. that a 10.6 wheel should be compatible with a 10.10 machine.

I'm not sure that is necessary for El Capitan, because pip 6 has been out for nearly a year now, but I could be persuaded either way.   It's just a one-line change in the building file if so, and the only cost is the increased ugliness of the wheel filename.

**Comment by ludwigschwardt** [comment]
Cool,

I'll give it a whirl then - time to take the plunge for El Capitan! I
completely skipped Yosemite... :-)

L.
