### ISSUE TITLE
Install error on RHEL using Python 2.7 and setup.py local

### ISSUE THREAD

**Issue by 12over7** [ludwigschwardt/python-gnureadline#48]
I'm attempting to install on RedHat using Python 2.7.  The system doesn't have internet access, so I'm using the setup method.  Looks like it can't find ncurses:

user@host:gnureadline-6.3.3> python setup.py install --user
.......
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_RL_CALLBACK -DHAVE_RL_CATCH_SIGNAL -DHAVE_RL_COMPLETION_APPEND_CHARACTER -DHAVE_RL_COMPLETION_DISPLAY_MATCHES_HOOK -DHAVE_RL_COMPLETION_MATCHES -DHAVE_RL_COMPLETION_SUPPRESS_APPEND -DHAVE_RL_PRE_INPUT_HOOK -I. -I/usr/local/include/python2.7 -c Modules/2.x/readline.c -o build/temp.linux-x86_64-2.7/Modules/2.x/readline.o
In file included from Modules/2.x/readline.c:31:
./readline/readline.h:385: warning: function declaration isnât a prototype
gcc -pthread -shared build/temp.linux-x86_64-2.7/Modules/2.x/readline.o readline/libreadline.a readline/libhistory.a -lncurses -o build/lib.linux-x86_64-2.7/gnureadline.so
/usr/bin/ld: cannot find -lncurses
collect2: ld returned 1 exit status
error: command 'gcc' failed with exit status 1

user@host:gnureadline-6.3.3> gcc -v
Using built-in specs.
Target: x86_64-redhat-linux
gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)

**Comment by ludwigschwardt** [comment]
Two questions:
- Do you have ncurses installed? I assume that it is a standard part of RedHat...
- Why install this package at all on RedHat, which presumably has a working GNU readline already installed? (the more important question!)

**Comment by 12over7** [comment]
ncurses-5.7-3.20090208.el6.x86_64 is installed.

I'm using a python package (steelscript) that requires readline.

**Comment by ludwigschwardt** [comment]
It could be that you need ncurses-devel too (although this error occurs during linking which makes me think that the library package only should be OK).

Is it this [steelscript](https://pypi.python.org/pypi/steelscript/)? I could not find any mention, either in documentation or the code, that suggests installing gnureadline... I would argue that you definitely don't need gnureadline on RedHat using its standard Python (unless you use ActiveState Python...).

If a third-party package forces you to install gnureadline on that system, the bug is with that package and should be fixed there by making gnureadline optional.

**Comment by 12over7** [comment]
metcr001@laccdndpv01:metcr001> steel about
Traceback (most recent call last):
  File "/home/net1/metcr001/.local/bin/steel", line 9, in <module>
    load_entry_point('steelscript==1.0.1', 'console_scripts', 'steel')()
  File "/home/net1/metcr001/.local/lib/python2.7/site-packages/steelscript-1.0.1-py2.7.egg/steelscript/commands/steel.py", line 1030, in run
    cmd.parse(sys.argv[1:])
  File "/home/net1/metcr001/.local/lib/python2.7/site-packages/steelscript-1.0.1-py2.7.egg/steelscript/commands/steel.py", line 270, in parse
    subcmds = [subcmd for subcmd in self.subcommands
  File "/home/net1/metcr001/.local/lib/python2.7/site-packages/steelscript-1.0.1-py2.7.egg/steelscript/commands/steel.py", line 362, in subcommands
    super(SteelCommand, self).subcommands
  File "/home/net1/metcr001/.local/lib/python2.7/site-packages/steelscript-1.0.1-py2.7.egg/steelscript/commands/steel.py", line 151, in subcommands
    self.load_subcommands()
  File "/home/net1/metcr001/.local/lib/python2.7/site-packages/steelscript-1.0.1-py2.7.egg/steelscript/commands/steel.py", line 247, in load_subcommands
    i = importlib.import_module(n)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/net1/metcr001/.local/lib/python2.7/site-packages/steelscript-1.0.1-py2.7.egg/steelscript/commands/rest.py", line 12, in <module>
    import readline
ImportError: No module named readline

**Comment by 12over7** [comment]
The box had Python 2.6 installed as an RPM.  Readline came with that 2.6 distribution.  SteelScript requires 2.7.  I had to install 2.7.11 from the standard distribution, because there is no RPM available.  It did not come with readline.

**Comment by 12over7** [comment]
I found a list of required packages for the python build.  We were missing several, and python didn't install those libraries as it should have.

It needed:  yum install gcc zlib-devel bzip2 bzip2-devel readline-devel sqlite sqlite-devel openssl-devel tk-devel gdbm-devel ncurses-devel glibc-devel git

Was missing:  
readline-devel
ncurses-devel
sqlite-devel
openssl-devel
git

**Comment by ludwigschwardt** [comment]
Just wanted to tell you the same thing! :-)

I found [this gist](https://gist.github.com/Brant/9993559) that showed the same issue. If you are going to install ncurses-devel you might as well install readline-devel directly and get it the normal way for Python.

If you install Python from the standard tarball at Python.org, it won't be able to install its dependencies so those are therefore up to you. That's one of the main reasons for going with the RPM instead.
