### ISSUE TITLE
broken after upgrade to Sierra / homebrew readline 7.0

### ISSUE THREAD

**Issue by anentropic** [ludwigschwardt/python-gnureadline#49]
I recently upgraded to Sierra

It was all working until I think what broke it is I did `brew upgrade` which upgraded all my installed homebrew packages

one of the things that came with that upgrade was readline 7.0

since then I have broken readline support in ipdb as described here:
http://stackoverflow.com/questions/39807946/arrow-keys-no-longer-work-in-python-shell-after-upgrading-mac-os-to-sierra
(iPython 5.1.0 works ok, problem is in ipdb)

I have tried

- `brew uninstall readline`
- `pip uninstall readline`
- `pip uninstall ipdb`
- `pip install gnureadline`
- `pip install ipdb`

(and also further combinations of uninstalling, `easy_install gnureadline`)

but it's still broken

I'd very much appreciate any help getting it working again :)

**Comment by anentropic** [comment]
also possibly implicated: homebrew pyenv

**Comment by ludwigschwardt** [comment]
Thanks for the report!

I need to bring out an update for the package soon anyway. I'm still on Mac
OS X but this will inspire me to try macOS :-)

**Comment by ludwigschwardt** [comment]
Just a reminder that the gnureadline package does not depend on the system
or Homebrew readline... I have my own internal version of the library,
statically linked in (v6.3.3 IIRC). So it won't be the upgrade to readline
7.0 that killed it.

**Comment by anentropic** [comment]
Thanks for your reply!

My situation was quite complicated, with homebrew, pyenv, virtualenv etc.  I don't think there is a problem with Sierra itself

I have been round in circles all morning uninstalling and reinstalling things

In the process my openssl stopped working (https://github.com/yyuu/pyenv/issues/745)

After the last step there (rebuild virtualenv using `pip --no-cache-dir`) now the arrow keys work fine in ipdb.  In fact I don't even have readline/gnureadline python packages installed at all, I think in recent OSX the system readline is ok? I vaguely remember seeing something about that.

**Comment by ludwigschwardt** [comment]
Actually IPython stopped using readline altogether - they use
prompt_toolkit now. So I'm off most hooks forever :-)

**Comment by anentropic** [comment]
ah that will be why, that's what I remembered reading
