### ISSUE TITLE
problem compiling on nixos

### ISSUE THREAD

**Issue by teto** [ludwigschwardt/python-gnureadline#51]
Hi,

I need to use python-gnureadline to get readline history in the cmd2 module but I have some trouble bringing it into nixos cf https://github.com/NixOS/nixpkgs/issues/31022.
I wonder if there is anything that requires the static readline
`extra_objects=['readline/libreadline.a', 'readline/libhistory.a']` and if I could not instead link to the system's readline.so ? I don't mean it as an upstream solution but as a local hack that can maybe added to the nixos package.

**Comment by ludwigschwardt** [comment]
Why would you need this package at all? Doesn't Python on NixOS - a Linux distribution - already use GNU readline for its readline module?

**Comment by teto** [comment]
Thanks for your great help on the issue. Problem solved as far as I am concerned.

**Comment by ludwigschwardt** [comment]
It's a pleasure. I only got back into supporting this package a few weeks ago - you're catching me at a good time!
