### ISSUE TITLE
about the error of gnureadline under macos arm architecture

### ISSUE THREAD

**Issue by ver007** [ludwigschwardt/python-gnureadline#57]
Hello, about the error of gnureadline under macos arm architecture, can you update the module, thank you

/usr/bin/python2.7 /Users/test/Application/python/test-Framework/v-framework.py
/Users/test/Application/python/test-Framework/libs/thirdparty/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
[2021-03-04 12:59:35] [CommonLog] [logger.py:135] Traceback (most recent call last):
  File "/Users/test/Application/python/test-Framework/v-framework.py", line 8, in <module>
    from libs.framework.terminal.main import Main
  File "/Users/test/Application/python/test-Framework/libs/framework/terminal/main.py", line 14, in <module>
    from libs.framework.terminal.base import BaseTerminal
  File "/Users/test/Application/python/test-Framework/libs/framework/terminal/base.py", line 15, in <module>
    from libs.framework.terminal.command.settab import commands, Completer
  File "/Users/test/Application/python/test-Framework/libs/framework/terminal/command/settab.py", line 17, in <module>
    import gnureadline as readline
ImportError: dlopen(/Users/test/Library/Python/2.7/lib/python/site-packages/gnureadline.so, 2): Symbol not found: _emacs_meta_keymap
  Referenced from: /Users/test/Library/Python/2.7/lib/python/site-packages/gnureadline.so
  Expected in: flat namespace
 in /Users/test/Library/Python/2.7/lib/python/site-packages/gnureadline.so

**Comment by ver007** [comment]
Hello, thank you for your reply. I downloaded and installed it using the python module repository, not using the source code

**Comment by zeev-mindali** [comment]
@ver007 did you able to install it?? I need to for mavproxy installation

**Comment by ludwigschwardt** [comment]
@ver007 @zeev-mindali Could you please try the Github version of the package to see if it fixes your problem? Thanks for any feedback!

**Comment by ludwigschwardt** [comment]
Hi @ver007 @zeev-mindali, gnureadline 8.1.2 has just been released on PyPI. Please check that it works for you.

**Comment by ludwigschwardt** [comment]
Fixed in 8.1.2.
