### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [ludwigschwardt/python-gnureadline#58]
Problem
---------
On aarch64, pip install gnureadline builds the wheels from source code and then install it. It requires user to have development environment installed on his system. also, it take some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, pip install gnureadline should download the wheels from pypi

@ludwigschwardt, Please let me know your interest on releasing aarch64 wheels. I can help in this.

**Comment by ludwigschwardt** [comment]
Interesting, haven't encountered that architecture before! I'm interested why you would need `gnureadline` - is it not part of the normal Python installation already?

**Comment by ModeSevenIndustrialSolutions** [comment]
Indeed, it seems this package isn't currently working on the Apple Silicon macOS machines.

I would be happy to collaborate on this issue to try and get it resolved. Unfortunately, some other Python tools, such as the Openstack CLI, produce constant warning output every time you invoke them, as they can't use/access the standard system bundled equivalents.

For example, this is the error macOS users see in their terminal window every time the openstack CLI utility is invoked:

% openstack server list
Readline features including tab completion have been disabled because
no supported version of readline was found. To resolve this, install
pyreadline3 on Windows or gnureadline on Linux/Mac.

I suspect there are likely to be other Python packages that are similarly affected. I would be happy to collaborate on finding a solution to this problem. Also, it is worth noting that a number of online providers now offer remote access to macOS M1 machines hosted in the cloud, such as:

Amazon AWS
  https://guce.techcrunch.com/copyConsent?sessionId=3_cc-session_4258aba4-d499-4894-a213-56524acd2041&lang=en-US
Scaleway
  https://www.scaleway.com/en/hello-m1/

Below is the error produced by the PIP installer. It simply doesn't recognise the CPU architecture, which usually means the configure scripts (or equivalent) need updating. I've been able to patch this manually in the past when installing some tarballs where the usual process is "configure/make/sudo make install". I'm not saying it is a trivial fix, but possibly not too much work?

python-gnureadline-master % pip install gnureadline 
Collecting gnureadline
  Using cached gnureadline-8.0.0.tar.gz (3.1 MB)
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for gnureadline, since package 'wheel' is not installed.
Installing collected packages: gnureadline
  Running setup.py install for gnureadline ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for gnureadline did not run successfully.
  │ exit code: 1
  ╰─> [197 lines of output]
      
      ============ Building the readline library ============
      
      Using compiler cc on OS X
      Guessing actual compiler: Apple clang version 13.1.6 (clang-1316.0.21.2.5)
      Compiler supports architectures: x86_64
      x readline-8.0/
      x readline-8.0/nls.c
      x readline-8.0/CHANGES
      x readline-8.0/histsearch.c
      x readline-8.0/readline.pc.in
      x readline-8.0/text.c
      x readline-8.0/chardefs.h
      x readline-8.0/histlib.h
      x readline-8.0/rlmbutil.h
      x readline-8.0/tilde.c
      x readline-8.0/colors.h
      x readline-8.0/vi_keymap.c
      x readline-8.0/keymaps.h
      x readline-8.0/histfile.c
      x readline-8.0/support/
      x readline-8.0/config.h.in
      x readline-8.0/util.c
      x readline-8.0/colors.c
      x readline-8.0/rltty.c
      x readline-8.0/posixjmp.h
      x readline-8.0/patchlevel
      x readline-8.0/rlwinsize.h
      x readline-8.0/misc.c
      x readline-8.0/funmap.c
      x readline-8.0/parse-colors.c
      x readline-8.0/signals.c
      x readline-8.0/configure
      x readline-8.0/INSTALL
      x readline-8.0/complete.c
      x readline-8.0/callback.c
      x readline-8.0/posixdir.h
      x readline-8.0/ansi_stdlib.h
      x readline-8.0/configure.ac
      x readline-8.0/xfree.c
      x readline-8.0/xmalloc.c
      x readline-8.0/undo.c
      x readline-8.0/rlconf.h
      x readline-8.0/shell.c
      x readline-8.0/CHANGELOG
      x readline-8.0/keymaps.c
      x readline-8.0/doc/
      x readline-8.0/readline.c
      x readline-8.0/mbutil.c
      x readline-8.0/COPYING
      x readline-8.0/display.c
      x readline-8.0/terminal.c
      x readline-8.0/parens.c
      x readline-8.0/README
      x readline-8.0/rlstdc.h
      x readline-8.0/posixselect.h
      x readline-8.0/history.c
      x readline-8.0/rltypedefs.h
      x readline-8.0/USAGE
      x readline-8.0/Makefile.in
      x readline-8.0/rlprivate.h
      x readline-8.0/aclocal.m4
      x readline-8.0/rlshell.h
      x readline-8.0/examples/
      x readline-8.0/shlib/
      x readline-8.0/histexpand.c
      x readline-8.0/compat.c
      x readline-8.0/readline.h
      x readline-8.0/tcap.h
      x readline-8.0/search.c
      x readline-8.0/macro.c
      x readline-8.0/rldefs.h
      x readline-8.0/MANIFEST
      x readline-8.0/tilde.h
      x readline-8.0/parse-colors.h
      x readline-8.0/vi_mode.c
      x readline-8.0/emacs_keymap.c
      x readline-8.0/isearch.c
      x readline-8.0/kill.c
      x readline-8.0/input.c
      x readline-8.0/NEWS
      x readline-8.0/rltty.h
      x readline-8.0/bind.c
      x readline-8.0/posixstat.h
      x readline-8.0/history.h
      x readline-8.0/savestring.c
      x readline-8.0/xmalloc.h
      x readline-8.0/shlib/Makefile.in
      x readline-8.0/examples/rlcat.c
      x readline-8.0/examples/excallback.c
      x readline-8.0/examples/rlwrap-0.30.tar.gz
      x readline-8.0/examples/rl-fgets.c
      x readline-8.0/examples/rlptytest.c
      x readline-8.0/examples/rlkeymaps.c
      x readline-8.0/examples/rl-callbacktest.c
      x readline-8.0/examples/rlbasic.c
      x readline-8.0/examples/readlinebuf.h
      x readline-8.0/examples/Inputrc
      x readline-8.0/examples/hist_erasedups.c
      x readline-8.0/examples/Makefile.in
      x readline-8.0/examples/rltest.c
      x readline-8.0/examples/autoconf/
      x readline-8.0/examples/manexamp.c
      x readline-8.0/examples/rlfe/
      x readline-8.0/examples/rlversion.c
      x readline-8.0/examples/rl.c
      x readline-8.0/examples/hist_purgecmd.c
      x readline-8.0/examples/rlevent.c
      x readline-8.0/examples/fileman.c
      x readline-8.0/examples/histexamp.c
      x readline-8.0/examples/rlfe/config.h.in
      x readline-8.0/examples/rlfe/configure
      x readline-8.0/examples/rlfe/pty.c
      x readline-8.0/examples/rlfe/rlfe.c
      x readline-8.0/examples/rlfe/ChangeLog
      x readline-8.0/examples/rlfe/README
      x readline-8.0/examples/rlfe/Makefile.in
      x readline-8.0/examples/rlfe/os.h
      x readline-8.0/examples/rlfe/extern.h
      x readline-8.0/examples/rlfe/screen.h
      x readline-8.0/examples/rlfe/configure.in
      x readline-8.0/examples/autoconf/wi_LIB_READLINE
      x readline-8.0/examples/autoconf/RL_LIB_READLINE_VERSION
      x readline-8.0/examples/autoconf/BASH_CHECK_LIB_TERMCAP
      x readline-8.0/doc/rluserman.pdf
      x readline-8.0/doc/texinfo.tex
      x readline-8.0/doc/readline.0
      x readline-8.0/doc/rluser.texi
      x readline-8.0/doc/readline.dvi
      x readline-8.0/doc/fdl.texi
      x readline-8.0/doc/hsuser.texi
      x readline-8.0/doc/rluserman.info
      x readline-8.0/doc/rltech.texi
      x readline-8.0/doc/rluserman.dvi
      x readline-8.0/doc/history.ps
      x readline-8.0/doc/readline_3.ps
      x readline-8.0/doc/rlman.texi
      x readline-8.0/doc/texi2html
      x readline-8.0/doc/readline.ps
      x readline-8.0/doc/history_3.ps
      x readline-8.0/doc/readline.info
      x readline-8.0/doc/readline.pdf
      x readline-8.0/doc/Makefile.in
      x readline-8.0/doc/readline.html
      x readline-8.0/doc/history.pdf
      x readline-8.0/doc/version.texi
      x readline-8.0/doc/history.3
      x readline-8.0/doc/history.texi
      x readline-8.0/doc/texi2dvi
      x readline-8.0/doc/hstech.texi
      x readline-8.0/doc/rluserman.texi
      x readline-8.0/doc/history.0
      x readline-8.0/doc/history.info
      x readline-8.0/doc/history.html
      x readline-8.0/doc/readline.3
      x readline-8.0/doc/history.dvi
      x readline-8.0/doc/rluserman.ps
      x readline-8.0/doc/rluserman.html
      x readline-8.0/support/config.sub
      x readline-8.0/support/mkinstalldirs
      x readline-8.0/support/shlib-install
      x readline-8.0/support/mkdist
      x readline-8.0/support/mkdirs
      x readline-8.0/support/install.sh
      x readline-8.0/support/config.rpath
      x readline-8.0/support/shobj-conf
      x readline-8.0/support/config.guess
      x readline-8.0/support/wcwidth.c
      checking build system type... Invalid configuration `arm64-apple-darwin21.5.0': machine `arm64-apple' not recognized
      configure: error: /bin/sh ./support/config.sub arm64-apple-darwin21.5.0 failed
      
      ============ Building the readline extension module ============
      
      running install
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-3.10
      copying readline.py -> build/lib.macosx-10.9-universal2-3.10
      running egg_info
      writing gnureadline.egg-info/PKG-INFO
      writing dependency_links to gnureadline.egg-info/dependency_links.txt
      writing top-level names to gnureadline.egg-info/top_level.txt
      reading manifest file 'gnureadline.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching 'readline*-0*' under directory 'rl'
      writing manifest file 'gnureadline.egg-info/SOURCES.txt'
      running build_ext
      building 'gnureadline' extension
      creating build/temp.macosx-10.9-universal2-3.10
      creating build/temp.macosx-10.9-universal2-3.10/Modules
      creating build/temp.macosx-10.9-universal2-3.10/Modules/3.x
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -DHAVE_RL_APPEND_HISTORY -DHAVE_RL_CALLBACK -DHAVE_RL_CATCH_SIGNAL -DHAVE_RL_COMPLETION_APPEND_CHARACTER -DHAVE_RL_COMPLETION_DISPLAY_MATCHES_HOOK -DHAVE_RL_COMPLETION_MATCHES -DHAVE_RL_COMPLETION_SUPPRESS_APPEND -DHAVE_RL_PRE_INPUT_HOOK -DHAVE_RL_RESIZE_TERMINAL -I. -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c Modules/3.x/readline.c -o build/temp.macosx-10.9-universal2-3.10/Modules/3.x/readline.o
      clang -bundle -undefined dynamic_lookup -arch arm64 -arch x86_64 -g build/temp.macosx-10.9-universal2-3.10/Modules/3.x/readline.o readline/libreadline.a readline/libhistory.a -lncurses -o build/lib.macosx-10.9-universal2-3.10/gnureadline.cpython-310-darwin.so
      clang: error: no such file or directory: 'readline/libreadline.a'
      clang: error: no such file or directory: 'readline/libhistory.a'
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> gnureadline

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by ludwigschwardt** [comment]
Thanks for pointing this out! I think readline 8.1 has support for aarch64 on Darwin, if I look at the configure script.

I was busy making an 8.1.2 release in February but got stuck with CI issues... I used Travis before but that is no longer looking good, so I want to move over to GitHub Actions. I also used to build wheels for many platforms via the [MacPython](https://github.com/MacPython/python-gnureadline-wheels) effort, but I'll have to rethink that too.

The good news is that I will soon have an M1 machine myself, which will help a lot 🙂

**Comment by ModeSevenIndustrialSolutions** [comment]
Ah, well this sounds very promising. I’ll do so, as soon as I’m back from holiday in Italy, in around ten days time. Thanks…

**Comment by ludwigschwardt** [comment]
Great! I might get my laptop before then :joy: Enjoy the break!

**Comment by ModeSevenIndustrialSolutions** [comment]
Almost forgot about this… Back from holiday, so will get to testing in the next few days. Did you get your M1 Mac?

- Matt

**Comment by ludwigschwardt** [comment]
Thanks Matt! I'm still soldiering on on the old laptop, but I did get to test the code on my colleague's M1.

I've been busy while you were away, upgrading the package all the way to Python 3.11.0a7 and adding a shiny new CI setup based on GitHub Actions.

You can now download preliminary M1 wheels directly from Actions [here](https://github.com/ludwigschwardt/python-gnureadline/actions/runs/2409882786#artifacts). Please try the universal2 wheel that matches your Python version.

**Comment by ModeSevenIndustrialSolutions** [comment]
No worries, I finally found the link here:
https://github.com/ludwigschwardt/python-gnureadline/suites/6715425862/artifacts/255725900
Let me try some test :-)

**Comment by ModeSevenIndustrialSolutions** [comment]
Works for me! The problem with the spurious warnings from the Openstack CLI tools is resolved once your package is installed. So, now to get your recent builds out there and published?

**Comment by ludwigschwardt** [comment]
Great, thanks a lot! Yeah, I also struggled to spot the artifacts at first...

I've started the process to build a final set of wheels (now also including arm64-only wheels) and will push to PyPI later today.

**Comment by ludwigschwardt** [comment]
OK, it is done! Please try 8.1.2 proper 😁

**Comment by ModeSevenIndustrialSolutions** [comment]
Done; the release version is now installed and working for me :-)

**Comment by ludwigschwardt** [comment]
Thanks for your patience and assistance - it's much appreciated!
