### ISSUE TITLE
Broken prompt

### ISSUE THREAD

**Issue by FleXoft** [ludwigschwardt/python-gnureadline#63]
In case of long lines in the history + if there are ANSI color escape sequences in the prompt, the historical up / down search is broken... **Is there any solution / suggestion to fix this wrong behaviour?**

**Comment by FleXoft** [comment]
Based on this article: https://stackoverflow.com/questions/50470933/readline-confused-by-ansi-escape-sequences I found a solution: **readline** expects **\001** and **\002** as markers around invisible characters!

**Comment by ludwigschwardt** [comment]
Wow György, thanks for digging that out! That is very useful to know 🙂
